close all; clear variables; clc;

kernel = @(x) mvnpdf(x);

parzen_singlePattern = @(x, xs, h, kernel) (h)^(-length(x)) * kernel((x - xs) ./ h);
parzen = @(x, xs, general_bandwidth, kernel) 1 / 3 * (...
    parzen_singlePattern(x, xs(1, :), general_bandwidth, kernel) + ...
    parzen_singlePattern(x, xs(2, :), general_bandwidth, kernel) + ...
    parzen_singlePattern(x, xs(3, :), general_bandwidth, kernel));

%% Shared Variables

xi_s = [-1.0, -1.0; ... 
        +0.0, +0.0; ...
        +0.5, +0.5];

x_s = [0.00, 0.0; ...
       0.25, 0.5; ...
       0.03, 0.4; ...
       0.72, 0.1; ...
       0.33, 0.2; ...
       0.24, 0.3];
general_bandwidth = 4;

%% Epanechnikov
for i = 1:size(x_s, 1)
    fprintf('gsl_vector_set(expected, %d, %2.15f);\n', ...
        i - 1, ...
        parzen(x_s(i, :), xi_s, general_bandwidth, kernel));
end